### ISSUE TITLE
xmlgen is not available on stable MELPA

### ISSUE THREAD

**Issue by rycee** [philjackson/xmlgen#2]
It would be very nice to have xmlgen on stable MELPA since, for example, the stable MELPA package [ocodo-svg-modelines](http://stable.melpa.org/#/ocodo-svg-modelines) has a dependency on xmlgen. Creating a stable package seems quite easy: https://github.com/milkypostman/melpa#stable-packages

**Comment by cap10morgan** [comment]
All that would be required is tagging a commit as "0.4", "v0.4", or similar. Then MELPA stable will pick it up and make it available.

Would be really nice to get that.

**Comment by cap10morgan** [comment]
@rycee I [uploaded it to Marmalade](https://marmalade-repo.org/packages/xmlgen) if you're willing to use that repo.

**Comment by rycee** [comment]
@cap10morgan, that works for me. Well I already had xmlgen installed manually but it's always nice to use a package. Thanks for uploading it!

**Comment by philjackson** [comment]
Sorry, guys. Completely missed this. Thanks again for sorting, @cap10morgan.

**Comment by ryoung786** [comment]
Hi @philjackson, I'm wondering if you'd still be up for tagging the repo - it'd be a huge help for those of us who'd like to fully stay on melpa stable!  I'd do it, but we can't submit tags through a pull request.

Something like this should do the trick:
```
git tag 0.4
git push origin 0.4
```

**Comment by philjackson** [comment]
Just pushed the tag - let me know if I screwed it up!

**Comment by ryoung786** [comment]
Yep, all set. http://stable.melpa.org/#/xmlgen

Thanks!
