### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by arunisaac** [philjackson/xmlgen#8]
Hi, I'm packaging xmlgen for GNU Guix. Can we have a new release, please? It's been a long while since the last release. In particular, I need the new ert tests. The current release uses the older etest tests.

Thank you!

**Comment by philjackson** [comment]
I've bumped the version and tagged it - if I remember, I think that's enough for a release?

**Comment by arunisaac** [comment]
Yes, that's it. Thanks!
